### ISSUE TITLE
Pushed: Starter Branch for AIW Main APP 

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#1]
@bogdandinchev 

I pushed py_08_28_01_aiw_main_app branch for your reference. 

Note: You can ignore the meta files required for our CI/CD process.

Pedro

**Comment by bogdandinchev** [comment]
[like]  Bogdan Dinchev reacted to your message:
________________________________
From: pedro-young-wedbush ***@***.***>
Sent: Wednesday, August 28, 2024 2:40:45 PM
To: InteropIO/wedbush-io-browser ***@***.***>
Cc: Bogdan Dinchev ***@***.***>; Mention ***@***.***>
Subject: [InteropIO/wedbush-io-browser] Pushed: Starter Branch for AIW Main APP (Issue #1)


@bogdandinchev<https://github.com/bogdandinchev>

I pushed py_08_28_01_aiw_main_app branch for your reference.

Note: You can ignore the meta files required for our CI/CD process.

Pedro
