### ISSUE TITLE
io.Manager and Server

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#10]
@bogdandinchev and @gganchev73,

Could you please share latest repo(s) for io.Manager (UI and Server)? We have not been able to upgrade from our current Glue42 version.

Pedro

**Comment by bogdandinchev** [comment]
Hey latest package of admin ui is: @interopio/manager-admin-ui^2.0.3 - check changelog https://docs.interop.io/manager/changelog/manager-admin-ui/index.html
latest package for ioManager is @interopio/manager: ^1.6.4 - check changelog https://docs.interop.io/manager/changelog/manager/index.html

The access to the packages is the same
