### ISSUE TITLE
Instructions on styling the main app 

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#3]
@bogdandinchev 

Please provide detailed instructions on styling the main app using Tailwind CSS. To illustrate your recommendations, please use the baseline app to create a new branch as an example.

**Comment by pedro-young-wedbush** [comment]
Using Tailwind CSS is ideal. We try to avoid with CSS directly if possible.

**Comment by pedro-young-wedbush** [comment]
@bogdandinchev - Are you able to work on this issue?

**Comment by gganchev73** [comment]
@pedro-young-wedbush 
Hi, Pedro! I have prepared a simple example: https://github.com/InteropIO/wedbush-io-browser/tree/mainapp_with_tailwindcss

I will send details shortly

**Comment by pedro-young-wedbush** [comment]
@gganchev73  and @bogdandinchev - Thank you! I will take a look at it and let you know.

**Comment by pedro-young-wedbush** [comment]
We are able to utilize Tailwind CSS. Thank you!
