### ISSUE TITLE
Update Workspace Tab Icon and Title

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#5]
@bogdandinchev and @gganchev73 

Could you please add codes to demo how to update the icon and title of a workspace including the default one?

![image](https://github.com/user-attachments/assets/b97a2539-2d47-451f-ae20-fcac443adc87)

**Comment by gganchev73** [comment]
@pedro-young-wedbush @bogdandinchev 
I will look into this.

**Comment by bogdandinchev** [comment]
Hey @pedro-young-wedbush,

Sorry it took longer - we had a National holiday in Bulgaria on Friday (so we were both off then) and I was off yesterday as well.

Together with @gganchev73 we prepared an example which is an implemented custom WorkspaceTabComponent- it is built upon the default existing one, but you have to manually extend all the components as we did - https://github.com/InteropIO/wedbush-io-browser/commit/b2e48b515c4ce4686190c95f38942ce1a2386e81

To change the title you must make changes in the WorkspaceTabV2.tsx file. We believe the naming is fine though, but if you insist you can do something like 
`const customTitle = title.startsWith('Untitled') ? 'New ' + title.split(' ')[1] : title`

The icon you can change in OptionsButton.tsx (we've provided an example with a dummy image)

**Comment by pedro-young-wedbush** [comment]
@bogdandinchev and @gganchev73 - Than you for the input.

We are able to customize the workspace tab title and icon:

![image](https://github.com/user-attachments/assets/b99063dc-282c-44ed-ae3b-05194240a82b)
