### ISSUE TITLE
SSO Integration with the Latest Interop.io

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#6]
@bogdandinchev  and @gganchev73 

Did the latest SSO pattern get released last week as you indicated earlier? If so, could you please share the details?

**Comment by bogdandinchev** [comment]
Hey,

The version containing the custom login is out:

You can display your custom login screen initially, after you get an authenticated user you can load the Home UI component. In the login config you can supply an object of this type:

type: 'custom';
  onLogout: () => void;
  user: CustomUser;




[cid:cf36eb09-e149-4664-bd55-898165a2679e]





Bogdan Dinchev



Consultant

***@***.***

________________________________
From: pedro-young-wedbush ***@***.***>
Sent: Tuesday, September 10, 2024 5:46 PM
To: InteropIO/wedbush-io-browser ***@***.***>
Cc: Bogdan Dinchev ***@***.***>; Mention ***@***.***>
Subject: [InteropIO/wedbush-io-browser] SSO Integration with the Latest Interop.io (Issue #6)


@bogdandinchev<https://github.com/bogdandinchev> and @gganchev73<https://github.com/gganchev73>

Did the latest SSO pattern get released last week as you indicated earlier? If so, could you please share the details?

**Comment by bogdandinchev** [comment]
I have committed an upgrade of the package in the repo: https://github.com/InteropIO/wedbush-io-browser/commit/544696af7b17550138a899349878626c9ae0ee63 The signature would look like this: login: {
        type: 'custom',
        onLogout: () => {
          // Custom logic when logging out
        },
   user: {
//the user obtained from your auth process
       id: string,
       username: string
      }
      }

type CustomUser = {
  id: string;
  username: string;
}



[cid:b7c0f45e-8876-4256-b0a2-ad7fe99bea5d]





Bogdan Dinchev



Consultant

***@***.***

________________________________

**Comment by pedro-young-wedbush** [comment]
@bogdandinchev, Thank you for the quick turnaround. The solution you provided seems to work for us.
