### ISSUE TITLE
 Implementing Context Change Auto-Refresh in Browser Version

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#8]
Hi @bogdandinchev  and @gganchev73 

Expected User Experience: When the context changes within a workspace, all apps that are subscribed to context change events should automatically refresh their pages.

Requirement: The current desktop behavior of automatic page refreshes upon context changes should be replicated in the browser version.

**Comment by bogdandinchev** [comment]
Hey Pedro,

This seems easy. In the 'demo-apps' branch of the repo we have provided an example with some simple applications that integrate, pass data and respond to context changes: https://github.com/InteropIO/wedbush-io-browser/tree/demo-apps. You may give it a look and if there is something more specific, we want to achieve - we'll go ahead and provide the necessary guidance!

Regards,


[cid:9aa646d8-2b8f-481f-a27a-d4897f8a96d7]





Bogdan Dinchev



Consultant

***@***.***

________________________________
From: pedro-young-wedbush ***@***.***>
Sent: Thursday, September 26, 2024 7:17 PM
To: InteropIO/wedbush-io-browser ***@***.***>
Cc: Bogdan Dinchev ***@***.***>; Mention ***@***.***>
Subject: [Ext] [InteropIO/wedbush-io-browser] Implementing Context Change Auto-Refresh in Browser Version (Issue #8)


Hi @bogdandinchev<https://github.com/bogdandinchev> and @gganchev73<https://github.com/gganchev73>

Expected User Experience: When the context changes within a workspace, all apps that are subscribed to context change events should automatically refresh their pages.

Requirement: The current desktop behavior of automatic page refreshes upon context changes should be replicated in the browser version.
